#!/bin/bash

file="$1"

[[ -z "$1" || ! -f "$file" || "${file##*.}" != "c" ]] && { echo "Usage: $0 <filename>"; exit 1; }
command -v gcc &>/dev/null || { echo "Error: gcc is not installed." >&2; exit 1; }

shift

gcc -o "${file%.c}" "$file" -pthread && "./${file%.c}" $@ && rm -f "${file%.c}"
